# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
        service:
          description: "Service to run"
          required: true
          type: choice
          options:
            - waterhose
            - consumer-graphql-api
            - nft-service
            - apps/main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: parseService
      if: ${{ startsWith(github.event.inputs.service, 'apps') }}
      env: 
        formatted: 'cmd/$github.event.inputs.service'
      run: echo $formatted >> $GITHUB_STEP_SUMMARY
    - name: Direct Parse
      run: echo resove expression ${{ startsWith(github.event.inputs.service, 'apps') && github.event.inputs.service || 'cmd/$github.event.inputs.service'}} >> $GITHUB_STEP_SUMMARY
